name = "MinimalPerfectHash"
uuid = "bb017ab8-e7aa-48c1-8510-d0c63904c71d"
authors = ["Kyungmin Lee"]
version = "0.2.0"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
